In [ ]:
* Подключение к базе данных
* Numpy
* Перевод массивов dataframe в Numpy
* Работа с формой массивов
* Работа с индексами
* Работа матрицами



In [49]:
import pandas as pd

In [46]:
data1 = {
        'client_id': ['1', '2', '3', '4', '5'],
        'Name': ['Ivan', 'Andrey', 'Mikhail', 'Alice', 'Olga'], 
        'Surname': ['A', 'B', 'C', 'D', 'E']}
df_a = pd.DataFrame(data1, columns = ['client_id', 'Name', 'Surname'])
df_a

client_id     Name Surname
0         1     Ivan       A
1         2   Andrey       B
2         3  Mikhail       C
3         4    Alice       D
4         5     Olga       E

In [47]:
data2 = {
        'client_id': ['4', '5', '6', '7', '8'],
        'Name': ['Dima', 'Fedor', 'Maxim', 'Sergey', 'Vladimir'], 
        'Surname': ['F', 'G', 'H', 'I', 'J']}
df_b = pd.DataFrame(data2, columns = ['client_id', 'Name', 'Surname'])
df_b

client_id      Name Surname
0         4      Dima       F
1         5     Fedor       G
2         6     Maxim       H
3         7    Sergey       I
4         8  Vladimir       J

In [52]:
pd.concat([df_a, df_b], ignore_index=True)

client_id      Name Surname
0         1      Ivan       A
1         2    Andrey       B
2         3   Mikhail       C
3         4     Alice       D
4         5      Olga       E
5         4      Dima       F
6         5     Fedor       G
7         6     Maxim       H
8         7    Sergey       I
9         8  Vladimir       J

In [53]:
pd.concat([df_a, df_b], ignore_index=True, axis=0)

client_id      Name Surname
0         1      Ivan       A
1         2    Andrey       B
2         3   Mikhail       C
3         4     Alice       D
4         5      Olga       E
5         4      Dima       F
6         5     Fedor       G
7         6     Maxim       H
8         7    Sergey       I
9         8  Vladimir       J

In [54]:
pd.concat([df_a, df_b], ignore_index=True, axis=1)

0        1  2  3         4  5
0  1     Ivan  A  4      Dima  F
1  2   Andrey  B  5     Fedor  G
2  3  Mikhail  C  6     Maxim  H
3  4    Alice  D  7    Sergey  I
4  5     Olga  E  8  Vladimir  J

In [ ]:
pd.concat , index true false, axis 0, axis 1
pd.merge , suffixes, left, right, inner, outer, left, right

In [55]:
data3 = {
        'client_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'product_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}
df_c = pd.DataFrame(data3, columns = ['client_id','product_id'])
df_c

client_id  product_id
0         1          51
1         2          15
2         3          15
3         4          61
4         5          16
5         7          14
6         8          15
7         9           1
8        10          61
9        11          16

In [57]:
pd.merge(df_a, df_c, on='client_id')

client_id     Name Surname  product_id
0         1     Ivan       A          51
1         2   Andrey       B          15
2         3  Mikhail       C          15
3         4    Alice       D          61
4         5     Olga       E          16

In [58]:
pd.merge(df_a, df_c, left_on='client_id', right_on='client_id')

client_id     Name Surname  product_id
0         1     Ivan       A          51
1         2   Andrey       B          15
2         3  Mikhail       C          15
3         4    Alice       D          61
4         5     Olga       E          16

In [ ]:
left right inner outer

In [60]:
pd.merge(df_a, df_c, on ='client_id', how='left')

client_id     Name Surname  product_id
0         1     Ivan       A          51
1         2   Andrey       B          15
2         3  Mikhail       C          15
3         4    Alice       D          61
4         5     Olga       E          16

In [61]:
pd.merge(df_a, df_c, on ='client_id', how='right')

client_id     Name Surname  product_id
0         1     Ivan       A          51
1         2   Andrey       B          15
2         3  Mikhail       C          15
3         4    Alice       D          61
4         5     Olga       E          16
5         7      NaN     NaN          14
6         8      NaN     NaN          15
7         9      NaN     NaN           1
8        10      NaN     NaN          61
9        11      NaN     NaN          16

In [62]:
pd.merge(df_a, df_c, on ='client_id', how='inner')

client_id     Name Surname  product_id
0         1     Ivan       A          51
1         2   Andrey       B          15
2         3  Mikhail       C          15
3         4    Alice       D          61
4         5     Olga       E          16

In [63]:
pd.merge(df_a, df_c, on ='client_id', how='outer')

client_id     Name Surname  product_id
0         1     Ivan       A          51
1         2   Andrey       B          15
2         3  Mikhail       C          15
3         4    Alice       D          61
4         5     Olga       E          16
5         7      NaN     NaN          14
6         8      NaN     NaN          15
7         9      NaN     NaN           1
8        10      NaN     NaN          61
9        11      NaN     NaN          16

In [ ]:
# numpy

In [64]:
import numpy as np

In [73]:
a = np.array([1,2,3,4])

In [66]:
a

array([1, 2, 3, 4])

In [67]:
type(a)

numpy.ndarray

In [69]:
a = np.array(['a',2,3,4])

In [70]:
a

array(['a', '2', '3', '4'], dtype='<U21')

In [71]:
b = np.array([1,5,3,6])

In [74]:
a+b

array([ 2,  7,  6, 10])

In [78]:
np.arange(0, 10, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [82]:
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [85]:
np.int32(10)

10

numpy.int32

In [86]:
np.int64(10)

10

In [88]:
a = np.zeros((3,5))

In [89]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [90]:
a = np.ones((3,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [91]:
a = np.full((3,5),-1)
a

array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

In [94]:
a = np.empty((3,3))
a

array([[ 0.  ,  1.25,  2.5 ],
       [ 3.75,  5.  ,  6.25],
       [ 7.5 ,  8.75, 10.  ]])

In [103]:
a=np.random.randint(0,10,size=(4,5))

In [99]:
a

array([[5, 5, 9, 0, 4],
       [6, 7, 8, 9, 4],
       [1, 4, 4, 3, 4]])

In [100]:
a.ravel()

array([5, 5, 9, 0, 4, 6, 7, 8, 9, 4, 1, 4, 4, 3, 4])

In [102]:
a.reshape(-1)

array([5, 5, 9, 0, 4, 6, 7, 8, 9, 4, 1, 4, 4, 3, 4])

In [104]:
a

array([[7, 7, 9, 4, 9],
       [5, 7, 9, 4, 7],
       [7, 2, 6, 3, 9],
       [8, 7, 2, 4, 2]])

In [105]:
a.reshape((2,10))

array([[7, 7, 9, 4, 9, 5, 7, 9, 4, 7],
       [7, 2, 6, 3, 9, 8, 7, 2, 4, 2]])

In [107]:
#np.lookfor('create array') 

In [108]:
a.ndim

2

In [109]:
a.shape

(4, 5)

In [110]:
a.size

20

In [111]:
a.dtype

dtype('int64')

In [112]:
a.itemsize

8

In [118]:
L=range(10000000)

In [119]:
%timeit [i ** 2 for i in L]

3.39 s ± 65.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [120]:
a = np.arange(10000000)

In [121]:
%timeit a**2

43.5 ms ± 3.58 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [123]:
np.array([1, 1, 1, 2]) == np.array([1, 1, 0, 2])

array([ True,  True, False,  True])

In [125]:
a=np.random.randint(0,10,size=(4,5))
a

array([[9, 6, 6, 3, 2],
       [0, 4, 2, 8, 2],
       [0, 4, 0, 6, 2],
       [8, 9, 6, 1, 9]])

In [126]:
b=np.random.randint(0,10,size=(5,4))
b

array([[3, 7, 5, 8],
       [2, 4, 6, 1],
       [9, 6, 9, 8],
       [0, 8, 6, 4],
       [7, 1, 9, 8]])

In [127]:
a.dot(b)

array([[107, 149, 171, 154],
       [ 40,  94, 108,  68],
       [ 22,  66,  78,  44],
       [159, 145, 235, 197]])

In [128]:
a@b

array([[107, 149, 171, 154],
       [ 40,  94, 108,  68],
       [ 22,  66,  78,  44],
       [159, 145, 235, 197]])

In [129]:
a*b

ValueError: operands could not be broadcast together with shapes (4,5) (5,4) 

In [130]:
c=np.random.randint(0,10,size=(4,5))
c

array([[5, 4, 4, 5, 9],
       [1, 3, 9, 2, 3],
       [9, 2, 0, 6, 9],
       [5, 0, 9, 9, 3]])

In [131]:
a*c

array([[45, 24, 24, 15, 18],
       [ 0, 12, 18, 16,  6],
       [ 0,  8,  0, 36, 18],
       [40,  0, 54,  9, 27]])

In [ ]:
np.put

In [ ]:
np.sort, np.argsort

In [132]:
c=np.random.randint(0,10,size=(1,5))

In [133]:
c

array([[5, 2, 4, 0, 6]])

In [134]:
c.shape

(1, 5)

In [135]:
c=np.random.randint(0,10,size=(5))

In [137]:
c

array([0, 3, 0, 7, 3])

In [138]:
c.shape

(5,)

In [139]:
c

array([0, 3, 0, 7, 3])

In [143]:
c2 = c[:, np.newaxis]

In [144]:
c2

array([[0],
       [3],
       [0],
       [7],
       [3]])

In [145]:
c2.shape

(5, 1)

In [147]:
c3=c[np.newaxis, :]

In [148]:
c3.shape

(1, 5)

In [149]:
c3

array([[0, 3, 0, 7, 3]])

In [153]:
c

array([0, 3, 0, 7, 3])

In [ ]:
c[np.newaxis, :]

In [150]:
c4=c[np.newaxis, np.newaxis, :]

array([[[0, 3, 0, 7, 3]]])

In [154]:
c[np.newaxis, np.newaxis,np.newaxis,np.newaxis,np.newaxis :]

array([[[[[0, 3, 0, 7, 3]]]]])

In [151]:
type(c)

numpy.ndarray

In [152]:
c.shape

(5,)

In [ ]:
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

In [155]:
a

array([[9, 6, 6, 3, 2],
       [0, 4, 2, 8, 2],
       [0, 4, 0, 6, 2],
       [8, 9, 6, 1, 9]])

In [159]:
np.where(a>5, a, -a)

array([[ 9,  6,  6, -3, -2],
       [ 0, -4, -2,  8, -2],
       [ 0, -4,  0,  6, -2],
       [ 8,  9,  6, -1,  9]])

In [161]:
np.where(a>5, True, False)

array([[ True,  True,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False,  True, False],
       [ True,  True,  True, False,  True]])

In [164]:
a=np.random.randint(0,10,size=(4,6))

In [165]:
a

array([[8, 3, 8, 8, 1, 2],
       [9, 5, 8, 0, 6, 5],
       [0, 1, 6, 8, 9, 7],
       [5, 2, 6, 4, 1, 4]])

In [166]:
b=np.random.randint(0,10,size=(4,6))
b

array([[2, 7, 9, 6, 9, 1],
       [8, 2, 3, 8, 3, 6],
       [4, 4, 0, 8, 1, 6],
       [1, 0, 3, 5, 6, 2]])

In [169]:
np.hstack((a,b))

array([[8, 3, 8, 8, 1, 2, 2, 7, 9, 6, 9, 1],
       [9, 5, 8, 0, 6, 5, 8, 2, 3, 8, 3, 6],
       [0, 1, 6, 8, 9, 7, 4, 4, 0, 8, 1, 6],
       [5, 2, 6, 4, 1, 4, 1, 0, 3, 5, 6, 2]])

In [170]:
np.vstack((a,b))

array([[8, 3, 8, 8, 1, 2],
       [9, 5, 8, 0, 6, 5],
       [0, 1, 6, 8, 9, 7],
       [5, 2, 6, 4, 1, 4],
       [2, 7, 9, 6, 9, 1],
       [8, 2, 3, 8, 3, 6],
       [4, 4, 0, 8, 1, 6],
       [1, 0, 3, 5, 6, 2]])

In [172]:
a=a.ravel()

In [173]:
a

array([8, 3, 8, 8, 1, 2, 9, 5, 8, 0, 6, 5, 0, 1, 6, 8, 9, 7, 5, 2, 6, 4,
       1, 4])

In [174]:
np.argmax(a)

6

In [175]:
a

array([8, 3, 8, 8, 1, 2, 9, 5, 8, 0, 6, 5, 0, 1, 6, 8, 9, 7, 5, 2, 6, 4,
       1, 4])

In [176]:
a=np.random.randint(0,10,size=(4,3))

In [177]:
a

array([[4, 0, 5],
       [0, 8, 9],
       [3, 0, 1],
       [0, 4, 9]])

In [178]:
b=np.random.randint(0,10,size=(4,3))
b

array([[1, 6, 4],
       [9, 4, 6],
       [5, 1, 7],
       [3, 6, 4]])

In [179]:
a+b

array([[ 5,  6,  9],
       [ 9, 12, 15],
       [ 8,  1,  8],
       [ 3, 10, 13]])

In [181]:
c=np.random.randint(0,10,size=(1,3))
c

array([[3, 9, 3]])

In [183]:
c.shape

(1, 3)

In [184]:
a+c

array([[ 7,  9,  8],
       [ 3, 17, 12],
       [ 6,  9,  4],
       [ 3, 13, 12]])

In [185]:
d=np.random.randint(0,10,size=(4,1))
d

array([[7],
       [9],
       [4],
       [8]])

In [186]:
d+c

array([[10, 16, 10],
       [12, 18, 12],
       [ 7, 13,  7],
       [11, 17, 11]])

In [ ]:



np.where, 
hstack, vstack

np.argmax(a)

broadcasting
np.tile(np.arange(0, 40, 10), (3, 1)).T + np.array([0, 1, 2])

In [ ]:
np.arange, 
сранение скоростей
L = range(1000)
%timeit [i**2 for i in L]

a = np.arange(1000)
%timeit a**2



np.lookfor('create array') 

type(np.int()), type(np.int32()), type(np.int64())

a.ndim, .shape, np.astype

np.random.choice

a.shape, a.ndim, a.size, a.dtype, a.itemsize,

сравнение
np.array([1, 1, 0, 2]) == np.array([1, 1, 0, 2])

np.linspace, np.logspace, np.ones, np.zeros, np.zero_like, np.full, np.empty,  np.random.random, .ravel(), a.reshape((3,4)), 

индексация, маскирование, арифметические операции, произведение dot и @, скалярное произведение, 



np.put, np.where, np.sort, np.argsort, np.newaxis

------------------------------

np.log, np.exp, np.round(x, n), a.mean(..axis=0), a.median(), np.min(), np.max()


#многомерные массивы
X = np.arange(24).reshape(2, 3, 4)

np.clip, np.tile, np.concatenate, np.meshgrid

broadcasting
np.tile(np.arange(0, 40, 10), (3, 1)).T + np.array([0, 1, 2])

hstack, vstack, mean, np.argmax(a), Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
* Перевод массивов dataframe в Numpy
* Работа с формой массивов * Работа с индексами * Работа матрицами, компонент linalg

np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


np.where, 
hstack, vstack

np.argmax(a)

broadcasting
np.tile(np.arange(0, 40, 10), (3, 1)).T + np.array([0, 1, 2])

In [42]:
np.meshgrid?

Signature: np.meshgrid(*xi, copy=True, sparse=False, indexing='xy')
Docstring:
Return coordinate matrices from coordinate vectors.

Make N-D coordinate arrays for vectorized evaluations of
N-D scalar/vector fields over N-D grids, given
one-dimensional coordinate arrays x1, x2,..., xn.

.. versionchanged:: 1.9
   1-D and 0-D cases are allowed.

Parameters
----------
x1, x2,..., xn : array_like
    1-D arrays representing the coordinates of a grid.
indexing : {'xy', 'ij'}, optional
    Cartesian ('xy', default) or matrix ('ij') indexing of output.
    See Notes for more details.

    .. versionadded:: 1.7.0
sparse : bool, optional
    If True a sparse grid is returned in order to conserve memory.
    Default is False.

    .. versionadded:: 1.7.0
copy : bool, optional
    If False, a view into the original arrays are returned in order to
    conserve memory.  Default is True.  Please note that
    ``sparse=False, copy=False`` will likely return non-contiguous
    arrays.  Furthermore, mo

In [17]:
import numpy as np

In [ ]:
np.random.*?

In [ ]:

b = np.array([[4, 1], [2, 2]])
print(a @ b)    # python 3 style
print(a.dot(b)) 

In [21]:
a = np.array([[1, 2], [0, 1], [3, 4]])

In [22]:
a

array([[1, 2],
       [0, 1],
       [3, 4]])

In [23]:
b = np.array([[4, 1, 5], [2, 2, 6]])

In [24]:
b

array([[4, 1, 5],
       [2, 2, 6]])

In [25]:
a@b

array([[ 8,  5, 17],
       [ 2,  2,  6],
       [20, 11, 39]])

In [26]:
a.dot(b)

array([[ 8,  5, 17],
       [ 2,  2,  6],
       [20, 11, 39]])

In [27]:
a*b

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [30]:
a.ravel()

array([1, 2, 0, 1, 3, 4])

In [31]:
np.argmax(a.ravel())

5