https://mset.space - платформа для проведения анализа данных, построения моделей и внедрения моделей в продукцию.


https://mset.space - platform for data analysis, model building and implementation into production.


Ноутбуки для платформы mset.space
https://github.com/MindSetLib/MS-Education

Low code ML - библиотека машинного обучения
https://github.com/MindSetLib/Insolver


Телеграм канал платформы
https://t.me/msetspace

Связь с разработчиками:
telegram: @frankshikhaliev
email: request@mind-set.ru

## Обучающий ноутбук по TensorFlow 2.x и сравнение TensorFlow 2.x с PyTorch

**Подготовил:** Гайфуллин Дмитрий, январь 2021 г.

### Описание ноутбука

В данном ноутбуке представлено краткое руководство по работе с фреймворком TensorFlow v.2.\
**Цель ноутбука:** рассмотрение основных методов TensorFlow, а также сравнение данного фреймворка с фреймворком PyTorch.

### TensorFlow

**TensorFlow** — открытая программная библиотека для машинного обучения, разработанная компанией Google для решения задач построения и тренировки нейронной сети с целью автоматического нахождения и классификации образов, достигая качества человеческого восприятия. Применяется как для исследований, так и для разработки собственных продуктов Google. Основной API для работы с библиотекой реализован для Python, также существуют реализации для R, C Sharp, C++, Haskell, Java, Go и Swift.

Является продолжением закрытого проекта DistBelief. Изначально TensorFlow была разработана командой Google Brain для внутреннего использования в Google, в 2015 году система была переведена в свободный доступ с открытой лицензией Apache 2.0.\

**Отличие TensorFlow 1.x от TensorFlow 2.x**

Основное преимущество TensorFlow – производительность. Этот инструмент создан для массового переноса моделей с уровня исследований в производство и фактически является промышленным станком для ИИ, но примерно таким же понятным для незнакомого с ним пользователя. Низкоуровневый TensorFlow 1.x труден для изучения и заставляет попотеть желающих открывать планеты или развивать медицину.

В TensorFlow 2.x по умолчанию в качестве режима выполнения моделей используется **Eager execution**. То есть вычисление конкретных значений происходит по ходу выполнения, до построения полного вычислительного графа. Это упрощает отладку моделей и устраняет необходимость в шаблонном коде. Таким образом, TensorFlow второй версии может поддерживать, как статический, так и динамический вычислительный граф.

Экосистема инструментов в TensorFlow 2.0 прошла тщательную очистку от конвейеров обработки данных до экспорта моделей в TensorBoard – инструмент для визуализации процесса обучения, отладки кода и оптимизации обучаемой модели. TensorBoard теперь совмещен с Keras.

На данный момент последней версией TensorFlow является 2.4.0.

### Импортируем библиотеку

In [39]:
# для установки второй версии используйте команду ниже
# !pip install -q tensorflow==2.1.0

# может появится ошибка: no module named opt_einsum
# она решается установкой: !conda install -c conda-forge opt_einsum

In [40]:
import warnings
warnings.filterwarnings("ignore") 

# импортируем TensorFlow и посмотрим на установленную версию
import tensorflow as tf
tf.__version__

'2.1.0'

### Тензоры

И PyTorch, и TensorFlow основаны на понятии Тензора (Tensor). Рассмотрим создание тензора у фреймворка TensorFlow.\
Если мы хотим создать неизменяющуюся переменную (константу, которая никогда не изменится), то следует использовать метод `tf.constant()`.\
Если мы хотим создать изменяющуюся переменную (например, вектор весов), то следует использовать метод `tf.Variable()`, данный метод есть и в PyTorch, однако, он имеет другое назначение.\
В официальных документах TensorFlow указано, что есть три типа тензоров:
   - tf.constant
   - tf.placeholder (только в TensorFlow 1.x)
   - tf.SparseTensor: особый вид тензора, которому на вход передается три параметра - indices (индексы элементов тензора, содержащие ненулевые значения), values (сами значения) и dense_shape (список, указывающий, сколько элементов содержит каждое измерение тензора)
   
При этом tf.Variable не классифицируется внутренне как тензор согласно классовой структуре.

In [3]:
# создадим переменные с помощью описанных выше методов
tf_var = tf.Variable([1, 2]) # тензор, который изменяется
tf_const = tf.constant([1, 2]) # тензор, который не изменяется
#tf_ph = tf..placeholder(tf.float32, shape=(2, 2))
tf_spts = tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])

print('tf_var:', tf_var)
print('tf_const', tf_const)
print('tf_spts', tf_spts)
print()
print('Type of tf.Variable is: ', type(tf_var))
print('Type of tf.constant is: ', type(tf_const))
#print('Type of tf.placeholder is: ', type(tf_ph))
print('Type of tf.SparseTensor is: ', type(tf_spts))

tf_var: <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>
tf_const tf.Tensor([1 2], shape=(2,), dtype=int32)
tf_spts SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))

Type of tf.Variable is:  <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
Type of tf.constant is:  <class 'tensorflow.python.framework.ops.EagerTensor'>
Type of tf.SparseTensor is:  <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'>


Создание тензоров, состоящих из нулей и единиц:

In [4]:
# слздание тензора типа int32, заполненного нулями
tensor = tf.zeros(shape=[3, 4], dtype=tf.int32)
print(tensor)
print()
# создание тензора типа float32, заполненного единицами 
tensor = tf.ones(shape=[5, 3], dtype=tf.float32)
print(tensor)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


Изменение типа тензора:

In [5]:
# создадим тензор из элементов типа float32
tensor = tf.constant([[3.1, 2.8],
                      [5.2, 2.3],
                      [9.7, 5.5],
                      [1.1, 3.4]], 
                      dtype=tf.float32)

# приведем элементы тензора к типу int32
tensor_as_int = tf.cast(tensor, tf.int32)

# посмотрим на тензор до изменения и после
print('Тензор до tf.cast:\n', tensor)
print('\nТензор после tf.cast:\n', tensor_as_int)

# заметим, что tf.cast округляет значения в меньшую сторону

Тензор до tf.cast:
 tf.Tensor(
[[3.1 2.8]
 [5.2 2.3]
 [9.7 5.5]
 [1.1 3.4]], shape=(4, 2), dtype=float32)

Тензор после tf.cast:
 tf.Tensor(
[[3 2]
 [5 2]
 [9 5]
 [1 3]], shape=(4, 2), dtype=int32)


Изменение формы тензора:

In [6]:
# создадим тензор для reshape
tensor = tf.constant([[3, 2],
                      [5, 2],
                      [9, 5],
                      [1, 3]])

# преобразуем тензор: shape = [rows, columns]
reshaped_tensor = tf.reshape(tensor = tensor,
                             shape = [1, 8])

print('tensor:', tensor)
print()
print('reshaped_tensor:', reshaped_tensor)

print()
print(('Тензор до reshape:\n{0}').format(tensor.shape))
print(('\nТензор после reshape:\n{0}').format(reshaped_tensor.shape))

tensor: tf.Tensor(
[[3 2]
 [5 2]
 [9 5]
 [1 3]], shape=(4, 2), dtype=int32)

reshaped_tensor: tf.Tensor([[3 2 5 2 9 5 1 3]], shape=(1, 8), dtype=int32)

Тензор до reshape:
(4, 2)

Тензор после reshape:
(1, 8)


Конкатенация тензоров:

In [7]:
# создадим константный тензор, который не изменяется
A = tf.constant([[3, 2],
                 [5, 2]])

# создадим еще один тензор
B = tf.constant([[9, 5],
                 [1, 3]])

print('Тензор А:\n', A)
print('\nТензор В:\n', B)
print()
# конкатенация по столбцам
AB_concatenated = tf.concat(values=[A, B], axis=1)
print('Добавление столбцов тензора B к А:\n',AB_concatenated)

# конкатенация по строкам
AB_concatenated = tf.concat(values=[A, B], axis=0)
print('\nДобавление строк тензора B к А:\n', AB_concatenated)

Тензор А:
 tf.Tensor(
[[3 2]
 [5 2]], shape=(2, 2), dtype=int32)

Тензор В:
 tf.Tensor(
[[9 5]
 [1 3]], shape=(2, 2), dtype=int32)

Добавление столбцов тензора B к А:
 tf.Tensor(
[[3 2 9 5]
 [5 2 1 3]], shape=(2, 4), dtype=int32)

Добавление строк тензора B к А:
 tf.Tensor(
[[3 2]
 [5 2]
 [9 5]
 [1 3]], shape=(4, 2), dtype=int32)


Различные операции с тензором:

In [8]:
# транспонирование тензора
# тензор
A = tf.constant([[3, 7],
                 [1, 9]])
print('Тензор:\n', A)
# транспонирование
B = tf.transpose(A)

print('\nРезультат транспонирования:\n', B)

Тензор:
 tf.Tensor(
[[3 7]
 [1 9]], shape=(2, 2), dtype=int32)

Результат транспонирования:
 tf.Tensor(
[[3 1]
 [7 9]], shape=(2, 2), dtype=int32)


In [9]:
# умножение тензоров
# матрица A 2х2
A = tf.constant([[3, 7],
                 [1, 9]])

# вектор v 2х1
v = tf.constant([[5],
                 [2]])

print('Матрица А:\n', A)
print('\nВектор V:\n', v)
print()
# матричное умножение
Av = tf.matmul(A, v)

print('Результат умножения:\n', Av)

Матрица А:
 tf.Tensor(
[[3 7]
 [1 9]], shape=(2, 2), dtype=int32)

Вектор V:
 tf.Tensor(
[[5]
 [2]], shape=(2, 1), dtype=int32)

Результат умножения:
 tf.Tensor(
[[29]
 [23]], shape=(2, 1), dtype=int32)


In [10]:
# поэлементное умножение
Av = tf.multiply(A, v)

print('Результат поэлементного умножения:\n', Av)

Результат поэлементного умножения:
 tf.Tensor(
[[15 35]
 [ 2 18]], shape=(2, 2), dtype=int32)


### Variable в TensorFlow и PyTorch

Сравним метод Variable в TensorFlow и PyTorch.\
Несколько фактов о Variable в TensorFlow:
   - tf.Variable на самом деле не является тензором, ее следует рассматривать как переменную;
   - tf.Variable - единственный тип, который может быть изменен;
   - tf.Variable спроектирован для весов и байеса, не для передачи в функции, как аргументов;
   - tf.Variable хранится отдельно, то есть не в вычислительном графе;
   - tf.Variable должен быть инициализирован до использования.
   
Рассмотрим Variable в TensorFlow:

In [11]:
# создадим переменную Variable
tf_var = tf.Variable([[1, 2], [3, 4]], tf.int32)
tf_var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [12]:
# посмотрим на ее тип
type(tf_var)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

**Вычисление градиентов.**

В TensorFlow реализован метод tf.GradientTape для отслеживания операций, произведенными над tf.Variable, для последующего вычисления градиентов.Ввиду того, что разные операции могут выполниться в ходе каждого вызова, все проходящие операции записаны на "ленту" ("tape"). Для вычисления градиента идем по ленте назад и затем останавливаемся. Отдельный tf.GradientTape может вычислить только один градиент, последовательные вызовы выбрасывают ошибки исполнения.\
Стоит заметить, что TensorFlow по-умолчанию следит за переменной Variable, отслеживая операции с ней, в отличие от PyTorch.\ 
Приведем пример.

In [17]:
x = tf.Variable(3.0)
with tf.GradientTape() as g:
    y = x ** 2
dy_dx = g.gradient(y, x)
print(dy_dx)

tf.Tensor(6.0, shape=(), dtype=float32)


Чтобы вычислить несколько градиентов, необходимо создать постоянную градиентную ленту: для этого нужно указать tf.GradientTape(persistent=True). Это позволяет многократно вызывать метод gradient () по мере высвобождения ресурсов при сборке мусора ленточного объекта. Например:

In [43]:
x = tf.Variable(3.0)
y = tf.Variable(4.0)
with tf.GradientTape(persistent=True) as g:
  #y = x * x
  z = x * (y**2)
dz_dx = g.gradient(z, x)
print(dz_dx)

dz_dy = g.gradient(z, y)
print(dz_dy)


tf.Tensor(16.0, shape=(), dtype=float32)
tf.Tensor(24.0, shape=(), dtype=float32)


Отличие данного метода от PyTorch состоит в том, что мы не сможем реализовать автоматическое дифференцирование переменных, не обернув их в tf.GradientTape.\
Реализуем программу, подгоняющую полигон третьей степени к функции синуса, с помощью методов TensorFlow.

In [38]:
import math

x = tf.linspace(-math.pi, math.pi, 2000)
y = tf.math.sin(x)

w_0 = tf.Variable(tf.random.normal(()))
w_1 = tf.Variable(tf.random.normal(()))
w_2 = tf.Variable(tf.random.normal(()))
w_3 = tf.Variable(tf.random.normal(()))

learning_rate = 1e-6
for t in range(2000):
    with tf.GradientTape(persistent=True) as g:
        y_pred =  w_0 + w_1 * x + w_2 * x ** 2 + w_3 * x ** 3
    
        loss = tf.math.reduce_sum((y_pred - y)**2)
        if t % 100 == 99:
            print(t, loss.numpy())
    
    # обновляем веса
    w_0.assign_sub(learning_rate * g.gradient(loss, w_0)) 
    w_1.assign_sub(learning_rate * g.gradient(loss, w_1))
    w_2.assign_sub(learning_rate * g.gradient(loss, w_2))
    w_3.assign_sub(learning_rate * g.gradient(loss, w_3))

print(f'Result: y = {w_0.numpy()} + {w_1.numpy()} x + {w_2.numpy()} x^2 + {w_3.numpy()} x^3')

99 2420.485
199 1603.5527
299 1063.3508
399 706.13794
499 469.92792
599 313.7318
699 210.4456
799 142.14651
899 96.98309
999 67.11804
1099 47.369514
1199 34.31051
1299 25.675125
1399 19.964783
1499 16.188728
1599 13.691779
1699 12.040627
1799 10.948765
1899 10.226723
1999 9.749285
Result: y = 0.0008136520045809448 + 0.8270718455314636 x + -0.00014036659558769315 x^2 + -0.08911023288965225 x^3


**Плюсы TensorFlow 2.x**
    
   - Теперь TensorFlow 2.x поддерживает как статический, так и динамический вычислительный граф;
   - Во вторую версию интегрирован Keras API;
   - Теперь не нужно создание сессий;
   - Для нее написано большое количество руководств и документации;
   - Она предлагает мощные средства мониторинга процесса обучения моделей и визуализации (Tensorboard);
   - Она поддерживается большим сообществом разработчиков и техническими компаниями;
   - Она обеспечивает обслуживание моделей;
    
**Минусы TensorFlow 2.x**

   - Она имеет более высокий входной порог для начинающих, чем PyTorch или Keras;
   - "Голая"s Tensorflow достаточно низкоуровневая и требует много шаблонного кода;
   - Трудно осуществлять debug, особенно на низком уровне (TensorFlow 1.x).

**Дополнительная информация**

1. Официальная страница: https://www.tensorflow.org/
2. Статья на Хабре: https://habr.com/ru/post/326650/
3. TensorFlow 2.x: https://mlfromscratch.com/tensorflow-2/