## Машинное обучение - 1
### 1. Решение задач кластеризации, классификации и регрессии с применением библиотек Python: scipy, numpy, pandas, matplotlib, sklearn. (повторение, на примерах из бизнеса).  


### 1.2 Вспоминаем NumPy

In [1]:
# Импортируем библиотеку numpy
import numpy as np

Билиотека **NumPy** предоставляет возможность работы с многомерными массивами с поддержкой выскоуровневых математических функций.

#### 1.2.1 Создание массивов  

Создать массив можно:
  -  Из структур Python (списки, кортежи)
  -  Прочитать с диска
  -  Встроенные средства создания массивов (arange, zeros, ones, random и т.п.)

In [2]:
# 1. Создание массива из списка
# Создадим массив, и проверим тип элементов в нём с помощью атрибута dtype
a = np.array([40, 50, 20, 30])
print(a, 'Тип элементов:', a.dtype)

[40 50 20 30] Тип элементов: int64


In [3]:
# 2. Явное указание типа
# Иногда требуется явно указать, какого типа будут элементы в создаваемом массиве
a = [10.9, 20]
b = [30, 40, 50, 60]
# Без указания типа получаем float64
c = np.array(a+b)
print(c, 'Тип элементов:', c.dtype)
# Можем оставить только целую часть, используя параметр dtype=np.int16
c = np.array(a+b, dtype=np.int16)
print(c, 'Тип элементов:', c.dtype)

[10.9 20.  30.  40.  50.  60. ] Тип элементов: float64
[10 20 30 40 50 60] Тип элементов: int16


In [4]:
# 3. Создание массива чтением с диска
# Создадим симуляцию файла с помощью функции StringIO
from io import StringIO
s_file = StringIO("""1,  , 1, 1, 1\n
                     2, 2,  , 2,  \n
                     3, 3,  ,  , 3\n""")
# Прочитаем файл с помощью функции genfromtxt.
# Укажем разделитель (парметр delimiter), без указания типа (параметр dtype)
a = np.genfromtxt(s_file, delimiter=",")
# Проверим
print(a, 'Тип элементов:', a.dtype)

[[ 1. nan  1.  1.  1.]
 [ 2.  2. nan  2. nan]
 [ 3.  3. nan nan  3.]] Тип элементов: float64


In [5]:
# 4. Создание массива с помощью генератора arange
# С помощью функции arange(start, stop, step, dtype) можно создать одномерный массив
# с перым элементом start (по умолчанию 0), последним элементом stop (не включён в массив),
# шагом step (по умолчанию 1) и типом dtype
# Если указан только 1 параметр, он используется как параметр stop
a = np.arange(5)
print(a, 'Тип элементов:', a.dtype)
# Если тип не указан, используется тип, подходящий под другие параметры
a = np.arange(5.)
print(a, 'Тип элементов:', a.dtype)

[0 1 2 3 4] Тип элементов: int64
[0. 1. 2. 3. 4.] Тип элементов: float64


In [6]:
# Шаг может быть отрицательным
a = np.arange(40, -30, -15)
print(a)
# Если между start и stop с шагом step нет ни одного элемента, в результате будет пустой массив
a = np.arange(1, 10, -1)
print(a)

[ 40  25  10  -5 -20]
[]


In [7]:
# 5. arange с вещественным шагом
# В связи с округлением (ceil((stop - start)/step)), при использовании вещественного шага step
# элемент stop может быть как не включён, так и включён в массив
# Стандартное поведение (stop не включён)
a = np.arange(.1, .3, .1)
print(a)
# Из-за округления stop включён
a = np.arange(.1, .4, .1)
print(a)
# В связи с этим, в случае вещественного шага рекомендуется использовать linspace

[0.1 0.2]
[0.1 0.2 0.3 0.4]


In [8]:
# 6. Создание массива с помощью генератора linspace
# Функция linspace возвращает одномерный массив из num элементов (по умолчанию 50)
# равномерно распределённых от start до stop.
# Если параметр endpoint=True (по умолчанию), элемент stop включается в массив
# Создадим массив из 10 элементов от 0 до 1, включая правую границу
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [9]:
# 7. Массив из нулей zeros
# Размерность требуемого массива передаётся в виде кортежа (x1, x2, ..., xn)
# Создадим массив из 3-х строк и 5 столбцов, в качестве параметра передаём кортеж  (3, 5)
a = np.zeros((3, 5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
# 8. Массив из единиц ones
# Массив из единиц создаётся аналогично массиву из нулей.
# Создадим массив из 3-х строк и 2 столбцов
a = np.ones((3,2))
print(a)
# И у zeros и у ones есть аналоги zeros_like и ones_like,
# которые создают новый массив с такой же размерностью, как и массив, переданный как параметр
# Создадим массив из нулей той же размерности, как и массив из единиц, созданный выше
b = np.zeros_like(a)
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
# 9. Массив из одинаковых значений full
# Мы можем заполнить массив не только нулями или единицами, но любой константой с функцией full
# Создадим массив из 2-х строк и 3-х столбцов и заполним его пятёрками.
c = np.full((2,3), 5)
print(c)

[[5 5 5]
 [5 5 5]]


In [12]:
# 10. Не инициализированный массив empty
# Мы можем создать массив необходимой размерности, не присваивая элементам значения
# Эта операция быстрее, чем создавать массив, например, из нулей
# В этом случае мы должны быть уверены, что далее присваивоим каждому элементу нужное значение
a = np.empty((2,2))
print(a)

[[0.1 0.2]
 [0.3 0.4]]


In [13]:
# 11. Случайные массивы random
# Создать массив со значениями случайно распределёнными от 0 до 1 (не включая 1) 
# можно с помощью функции random.random. Параметром передаётся размерность массива
# Создадим одномерный массив из 5 элементов
print(np.random.random(5))
# Создадим двумерный массив 2Х2
print(np.random.random((2,2)))

[0.5012353  0.54166144 0.06714113 0.7194587  0.11454614]
[[0.78505737 0.13671427]
 [0.07840766 0.49403722]]


In [14]:
# 12. Случайные массивы randint
# В numpy множество вариантов создания массива со случайными значениями.
# Приведём ещё один вариант: random.randint(low, high, size)
# Эта функция создаёт массив размерности size (по умолчанию - одно значение),
# заполненный целыми значениями случайно распределёнными от low (включительно) до high (не включительно)
print(np.random.randint(1, 10, (5,5)))

[[9 8 4 2 7]
 [7 8 6 3 3]
 [9 1 7 1 4]
 [8 1 9 3 2]
 [5 8 3 1 2]]


In [15]:
# 13. Перевод массива pandas.DataFrame в массив numpy, values
# Создадим DataFrame из 2-х столбцов
import pandas as pd
dfA = pd.DataFrame({'c1': [1, 1, 1],
                    'c2': [2.1, 2.2, 2.3]})
# Для того, чтобы получить массив Numpy можно использовать метод values
a = dfA.values
# Проверим тип и размер получившегося объекта и выведем сам объект
print('Тип: ', type(a))
print('Размер:', a.shape)
print(a)

Тип:  <class 'numpy.ndarray'>
Размер: (3, 2)
[[1.  2.1]
 [1.  2.2]
 [1.  2.3]]


In [16]:
# 14. Перевод массива pandas.DataFrame в массив numpy, to_numpy
# В документации рекомендованным методом для конвертации DataFrame в numpy.ndarray
# указывается метод to_numpy
# Используем to_numpy на DataFrame, созданный выше
a = dfA.to_numpy()
# Проверим тип и размер получившегося объекта и выведем сам объект
print('Тип: ', type(a))
print('Размер:', a.shape)
print(a)

Тип:  <class 'numpy.ndarray'>
Размер: (3, 2)
[[1.  2.1]
 [1.  2.2]
 [1.  2.3]]


In [17]:
# 15. Перевод pandas.Series в numpy через to_numpy
# Для объектов Series работает такой же метод to_numpy
# Создадим массив из первого столбца DataFrame из примера выше
s = dfA['c1']
# Убедимся, что работаем с серией
print(type(s))
a = s.to_numpy()
print('Тип: ', type(a))
print('Размер:', a.shape)
# В результате получается одномерный массив
print(a)

<class 'pandas.core.series.Series'>
Тип:  <class 'numpy.ndarray'>
Размер: (3,)
[1 1 1]


#### 1.2.2 Форма

In [18]:
# 16. Размер shape и количество размерностей ndim
# Для того, чтобы посмотреть количество размерностей массива, используем ndim
# Количество строк и столбцов (и размер других осей, при наличии) можно вывести с shape
a = np.zeros((2,3,4,5))
print('Размерностей: ', a.ndim, ', Размер: ', a.shape)

Размерностей:  4 , Размер:  (2, 3, 4, 5)


In [19]:
# 17. Перевод многомерного массива в одномерный, ravel
a = np.ones((3,2))
print('Исходный массив')
print(a)
b = a.ravel()
print('Одномерное представление исходного массива')
print(b)

Исходный массив
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Одномерное представление исходного массива
[1. 1. 1. 1. 1. 1.]


In [20]:
# 18. Изменение формы reshape
# Для изменения формы массива можно использовать reshape
# В качестве параметра передаётся кортеж с размерами по каждой оси
# Создадим одномерный массив от 1 до 12, представим его в двумерном виде 3Х4
a = np.arange(1, 13)
print('Исходный массив')
print(a)
b = a.reshape((3,4))
print('Двумерное представление исходного массива')
print(b)

Исходный массив
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Двумерное представление исходного массива
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
# 19. Изменение формы reshape, Fortran-order
# По умолчанию используется порядок C-order: сначала заполняются столбцы, потом строки
# Можно использовать F-order: сначала заполняются строки, потом столбцы
# В этом случае результирующий массив из примера выше будет выглядеть так
b = a.reshape((3,4), order='F')
print('Двумерное представление исходного массива (F-order)')
print(b)

Двумерное представление исходного массива (F-order)
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [22]:
# 20. Изменение формы reshape, размер -1
# Мы можем использовать в качестве размеров "-1"
# В этом случае этот размер будет определён исходя из количества элементов и остальных размеров
a = np.arange(1, 13)
print('Исходный массив')
print(a)
# Создадим двумерный массив с 6-ю столбцами. Количество строк определится автоматически.
b = a.reshape((-1,6))
print('Двумерное представление исходного массива')
print(b)

Исходный массив
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Двумерное представление исходного массива
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [23]:
# 21. Изменение формы reshape, view
# С помощью reshape (а также ravel) мы не создаём новую копию объекта
# Мы создаём его новое представление (view).
# При изменениях значений элементов view мы меняем также и исходный массив
# Продемонстрируем это. Создадим новый массив
a = np.arange(1, 13)
print('Исходный массив')
print(a)
# Создадим новое представление 3х4 и заменим среднюю строку на нули
b = a.reshape((3,4))
b[1,:] = 0
print('Двумерное представление исходного массива, с изменениями')
print(b)
# Выведем исходный массив. В нём отразились сделанные нами изменения.
print('Исходный массив')
print(a)
# Для того, чтобы при изменении формы создавать новый массив, нужно воспользоваться методом copy
# Для ravel есть аналог - метод flatten, также преоброзающий массив в одномерный, но делающий копию

Исходный массив
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Двумерное представление исходного массива, с изменениями
[[ 1  2  3  4]
 [ 0  0  0  0]
 [ 9 10 11 12]]
Исходный массив
[ 1  2  3  4  0  0  0  0  9 10 11 12]


In [24]:
# 22. Фиктивная размерность newaxis
# С помощью функции newaxis мы можем добавлять фиктивную размерность.
# Т.е. при неизменном количестве элементов, мы повышаем размерность.
# Создадим новый одномерный массив из 5 элементов
a = np.arange(5)
print('Исходный массив')
print(a)
print('Исходный размер: ', a.shape)
# Превратим одномерный массив в двумерный массив, содержащий 1 строку и  5 столбцов
b = a[np.newaxis, :]
print('Двумерный массив с 1-й строкой')
print(b)
print('Размер: ', b.shape)
# Превратим одномерный массив в двумерный массив, содержащий 5 строк и  1 столбец
b = a[:, np.newaxis]
print('Двумерный массив с 1-м столбцом')
print(b)
print('Размер: ', b.shape)

Исходный массив
[0 1 2 3 4]
Исходный размер:  (5,)
Двумерный массив с 1-й строкой
[[0 1 2 3 4]]
Размер:  (1, 5)
Двумерный массив с 1-м столбцом
[[0]
 [1]
 [2]
 [3]
 [4]]
Размер:  (5, 1)


#### 1.2.3 Индексация

In [25]:
# 23. Выбор одного элемента по координатам
# Один элемент можно выбрать, указав в квадратных скобках координаты через запятую
# Например, для двумерного массива: Array[i, j], где i - номер строки, j - номер столбца.
# Нумерация строк и столбцов начинается с 0
# Поменяем элемент в 2-й строке, 3-м столбце на единицу
a = np.zeros((5,5))
a[2, 3] = 1
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
# 24. Выбор одной строки
# Для того, чтобы выбрать одну строку, в качестве координаты столбца
# указываем двоеточие, т.е. все элементы столбца
# Изменим все элементы 3-й строки
a = np.zeros((5,5))
a[3, :] = 1
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]


In [27]:
# 25. Выбор одного столбца
# Аналогично, чтобы выбрать один столбец - вместо координаты строки указываем ":"
# Изменим все элементы 1-го столбца (напомним, что нумерация начинается с нуля)
a = np.zeros((5,5))
a[:, 1] = 1
print(a)

[[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


В предыдущих примерах мы использовали ":", это синтаксис "среза" (slice) в Python.  
В массивах **numpy** срезы работают так же, как в списках Python, но есть существенное отличие.  
**При использовании slice в массивах numpy возвращается не копия массива, а его представление (view)**. За счёт этого, можно с помощью slicing менять значения в массиве (что мы и делали выше).  

Напомним синтаксис slice  
Диапазон координат указываем в виде start:stop:step, где
  -  start - начало диапазона
  -  stop - конец диапазона (не включается)
  -  step - шаг 

В случае отсутствия start, в качестве начала диапазона используется первый элемент.  
В случае отсутствия stop - концом будет последний элемент.  
Если ни start ни end не указаны, выбираются все элементы (это мы уже делали выше).  
По умолчанию шаг используется равным 1 (т.е. выбираем все элементы от start до stop).  
Шаг может быть отрицательным, тогда перебираем элементы в обратном направлении.

In [28]:
# 26. Часть одной строки
# Далее рассмотрим ещё несколько примеров применения срезов.
# Изменим в 3-й строке элементы, начиная с 2-го
a = np.zeros((5,5))
a[3, 2:] = 1
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]


In [29]:
# 27. Часть одного столбца
# Аналогично для выбора части столбца
# Изменим в 0-м столбце все элементы до 3-го
# Обратите внимание, для этого мы указываем 4 в качестве конца диапазона
a = np.zeros((5,5))
a[:4, 0] = 1
print(a)

[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
# 28. Непрерывная часть массива
# Изменим все элементы с 1-й по 3-ю строку и с 2-го по 3-й столбец
a = np.zeros((5,5))
a[1:4, 2:4] = 1
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [31]:
# 29. Срез с шагом 2
# Заполним массив единицами в шахматном порядке
# Для этого дважды используем срезы с шагом 2, с диагональным смещением оносительно друг друга
# Первый срез будет начинаться в координате 0,1 (запись [::2, 1::2])
# Второй - начинается в координате 1,0 (запись [1::2, ::2])
a = np.zeros((5,5))
a[::2, 1::2] = 1
a[1::2, ::2] = 1
print(a)

[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


In [32]:
# 30. Срез с шагом -1
# Развернём массив в обратном порядке
# Для этого и для строк и для столбцов используем конструкцию [::-1]
# Т.к. start и stop не указаны, берём всю строку (столбец) от последнего элемента к первому
a = np.arange(25).reshape(5, 5)
print('Исходный массив')
print(a)
b = a[::-1, ::-1]
print('Обращённый массив')
print(b)

Исходный массив
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Обращённый массив
[[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


In [33]:
# 31. Передача индексов списком
# Мы можем передавать нужные номера столбцов и строк в виде списков
# Сделаем замену всех крайних элементов на единицы
# Для этого дважды используем список borders = [0, -1], для строк и столбцов
a = np.zeros((5,5))
borders = [0, -1]
a[borders, :] = 1
a[:, borders] = 1
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [34]:
# 32. Индексирование по условию (маска)
# Можно задать элементы для выборки с помощью маски -
# массива аналогичной размерности, заполненного элементами True и False
# Маску можно задать вручную, или получить её как результат условия для массива
# Например, выберем только те элементы массива, значения которых кратны 3 (условие a % 3 == 0)
a = np.arange(25).reshape(5, 5)
print('Исходный массив')
print(a)
mask = a % 3 == 0
print('Маска: элементы массива, кратные 3')
print(mask)
# С помощью этой маски поменяем знак у найденных элементов на противоположный
a[mask] *= -1
print('Полученный массив')
print(a)

Исходный массив
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Маска: элементы массива, кратные 3
[[ True False False  True False]
 [False  True False False  True]
 [False False  True False False]
 [ True False False  True False]
 [False  True False False  True]]
Полученный массив
[[  0   1   2  -3   4]
 [  5  -6   7   8  -9]
 [ 10  11 -12  13  14]
 [-15  16  17 -18  19]
 [ 20 -21  22  23 -24]]


In [35]:
# 33. Выбор элементов по условию, where
# С помощью функции where также изменить элементы в соответствии с условием
# Вызов выглядит как where(условие,изменение_если_условие_верно,изменение_если_условие_не_верно)
# Создадим массив 5х5 из случайных значений от 1 до 29 включительно.
# Если значение элемента больше 25, берём 100, если меньше - 0
a = np.random.randint(1, 30, (5,5))
print('Исходный массив')
print(a)
b = np.where(a > 25, 100, 0)
print('Полученный массив')
print(b)

Исходный массив
[[28 12 12  9 10]
 [22  5 21 17  6]
 [ 7  9 18  3 17]
 [29 18 17 21 15]
 [20 11  6  8 25]]
Полученный массив
[[100   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [100   0   0   0   0]
 [  0   0   0   0   0]]


#### 1.2.4 Работа с матрицами

In [36]:
# 34. Арифметические операции
# При одинаковой размерности, арифметические операции между массивами производятся поэлементно
# Создадим 2 массива
a = np.arange(10, 50, 10).reshape(2,2)
print('Исходный массив A')
print(a)
b = np.arange(1, 5).reshape(2,2)
print('Исходный массив B')
print(b)
# Выведем результат сложения, вычитания, умножения, деления
print('A + B')
print(a + b)
print('A - B')
print(a - b)
print('A * B')
print(a * b)
print('A / B')
print(a / b)

Исходный массив A
[[10 20]
 [30 40]]
Исходный массив B
[[1 2]
 [3 4]]
A + B
[[11 22]
 [33 44]]
A - B
[[ 9 18]
 [27 36]]
A * B
[[ 10  40]
 [ 90 160]]
A / B
[[10. 10.]
 [10. 10.]]


In [37]:
# 35. Broadcasting
# Также можно проводить арифметические операции над массивами не с одинаковой,
# но с согласованной размерностью.
# Согласованными считаются размерности если они либо равны, либо одна из них равна 1.
# Так, например, у массивов 2х3 и 2х1 размерности согласованы.
# А у массивов 2х3 и 3х1 - не согласованы.
# Для того, чтобы сложить поэлементно одномерный массив и двумерный,
# потребуется добавление фиктивной размерности одномерному массиву.
a = np.arange(6).reshape(2,3)
print('Исходный массив A')
print(a)
print('Исходный размер A: ', a.shape)
b = np.ones(3)
print('Исходный массив B')
print(b)
print('Исходный размер B: ', b.shape)
print('Фиктивный размер B: ', b[np.newaxis,:].shape)
print('A + B')
print(a + b[np.newaxis,:])

Исходный массив A
[[0 1 2]
 [3 4 5]]
Исходный размер A:  (2, 3)
Исходный массив B
[1. 1. 1.]
Исходный размер B:  (3,)
Фиктивный размер B:  (1, 3)
A + B
[[1. 2. 3.]
 [4. 5. 6.]]


In [38]:
# 36. Скалярное произведение dot
# Для того, чтобы скалярно перемножить 2 матрицы, используется функция dot
a = np.arange(6).reshape(2,3)
print('Исходный массив A')
print(a)
b = np.arange(5,-1,-1).reshape(3,2)
print('Исходный массив B')
print(b)
print('A*B')
print(np.dot(a, b))

Исходный массив A
[[0 1 2]
 [3 4 5]]
Исходный массив B
[[5 4]
 [3 2]
 [1 0]]
A*B
[[ 5  2]
 [32 20]]


In [39]:
# 37. Транспонирование
# Для транспонирования матрицы используется метод T
a = np.arange(6).reshape(2,3)
print('Исходный массив A')
print(a)
print('AT')
print(a.T)

Исходный массив A
[[0 1 2]
 [3 4 5]]
AT
[[0 3]
 [1 4]
 [2 5]]


In [40]:
# 38. Математические функции
# В Numpy есть множество встроенных математических функций,
# которые выполняются над каждым элементом массива
a = np.arange(1, 5).reshape(2,2)
print('Исходный массив')
print(a)
# Например, косинус или логарифм
print('cos(a)')
print(np.cos(a))
print('log10(a)')
print(np.log10(a))

Исходный массив
[[1 2]
 [3 4]]
cos(a)
[[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]
log10(a)
[[0.         0.30103   ]
 [0.47712125 0.60205999]]


In [41]:
# 39. Объединение массивов, hstack
# Можно "склеить" два массива по горизонтали (один справа от другого) с помощью hstack
# Создадим 2 массива с одинаковым количеством строк, и объединим их
a = np.arange(4).reshape(2,2)
print('Исходный массив A')
print(a)
b = np.arange(10,70,10).reshape(2,3)
print('Исходный массив B')
print(b)
print('AB')
print(np.hstack((a, b)))

Исходный массив A
[[0 1]
 [2 3]]
Исходный массив B
[[10 20 30]
 [40 50 60]]
AB
[[ 0  1 10 20 30]
 [ 2  3 40 50 60]]


In [42]:
# 40. Объединение массивов, vstack
# Можно объединить два массива по вертикали (поставить один на другой) с помощью vstack
a = np.arange(6).reshape(2,3)
print('Исходный массив A')
print(a)
b = np.arange(10,100,10).reshape(3,3)
print('Исходный массив B')
print(b)
print('AB')
print(np.vstack((a, b)))

Исходный массив A
[[0 1 2]
 [3 4 5]]
Исходный массив B
[[10 20 30]
 [40 50 60]
 [70 80 90]]
AB
[[ 0  1  2]
 [ 3  4  5]
 [10 20 30]
 [40 50 60]
 [70 80 90]]


In [43]:
# 41. Максимум, минимум, среднее и т.д.
# Для нахождения максимального и минимального элемента в массиве используются max() и min()
a = np.random.randint(1, 30, (5,5))
print('Исходный массив')
print(a)
print('Максимальное значение', np.max(a))
print('Минимальное значение', np.min(a))
print('Среднее', np.mean(a))

Исходный массив
[[11  9 16 27  4]
 [11 10 26  6  5]
 [16 20 17 28 16]
 [ 1 15 11  9  9]
 [22 17 23 14 18]]
Максимальное значение 28
Минимальное значение 1
Среднее 14.44


In [44]:
# 42. Максимум и т.д., по одному измерению
# Для того, чтобы найти максимум (минимум, среднее, сумму и т.д.) по каждой строке,
# используем параметр axis=1
# Соответственно, для подсчёта по столбцам - axis=0
a = np.random.randint(1, 30, (5,5))
print('Исходный массив')
print(a)
print('Максимальное значение в каждой строке', np.max(a, axis=1))
print('Максимальное значение в каждом столбце', np.max(a, axis=0))

Исходный массив
[[15 18 14 24 21]
 [14  7 10  3 23]
 [27 27  7  7 20]
 [16 27 21 21 23]
 [23 19  9 24 26]]
Максимальное значение в каждой строке [24 23 27 27 26]
Максимальное значение в каждом столбце [27 27 21 24 26]


In [45]:
# 43. Координаты максимального элемента, argmax
# Координату элемента с максимальным значением можно узнать с помощью метода argmax
# Можно использовать для замены максимального элемента
a = np.random.randint(1, 30, (5,5))
print('Исходный массив')
print(a)
print('Максимальное значение', np.max(a))
print('Координаты максимального элемента', np.argmax(a))
# Координату argmax возвращает в одномерном представлении.
# С помощью ravel опращаемся к одномерному представлению по координате, и меняем элемент на -100
a.ravel()[a.argmax()] = -100
print('Полученный массив')
print(a)

Исходный массив
[[21  5 22 20  2]
 [25 18  8 25 10]
 [17  2 10  7  7]
 [11 27 13 22  6]
 [ 2  7 17 10  3]]
Максимальное значение 27
Координаты максимального элемента 16
Полученный массив
[[  21    5   22   20    2]
 [  25   18    8   25   10]
 [  17    2   10    7    7]
 [  11 -100   13   22    6]
 [   2    7   17   10    3]]


In [46]:
# 44. Модуль linalg, собственные значения eig
# В модуле linalg собраны функции из линейной алгебры
# Рассмотрим несколько из них
# Собственные значения и вектора матрицы можно найти с помощью функции eig
a = np.arange(4).reshape(2,2)
print('Исходный массив')
print(a)
w, v = np.linalg.eig(a)
print('Собственные значения', w)
print('Собственные вектора')
print(v)

Исходный массив
[[0 1]
 [2 3]]
Собственные значения [-0.56155281  3.56155281]
Собственные вектора
[[-0.87192821 -0.27032301]
 [ 0.48963374 -0.96276969]]


In [47]:
# 45. Модуль linalg, определитель det
a = np.arange(4).reshape(2,2)
print('Исходный массив')
print(a)
print('Определитель', np.linalg.det(a))

Исходный массив
[[0 1]
 [2 3]]
Определитель -2.0


In [48]:
# 46. Модуль linalg, норма norm
a = np.arange(4).reshape(2,2)
print('Исходный массив')
print(a)
print('Норма', np.linalg.norm(a))

Исходный массив
[[0 1]
 [2 3]]
Норма 3.7416573867739413


#### Ресурсы
  -  Официальная документация NumPy https://docs.scipy.org/doc/numpy/user/quickstart.html
  -  100 numpy exercises - сборник из 100 коротких примеров по numpy, дающих представление о возможностях numpy https://github.com/rougier/numpy-100
  -  Разнообразные учебные материалы, например ChEng UC https://engineering.ucsb.edu/~shell/che210d/numpy.pdf
  -  ВМК МГУ https://github.com/mmp-practicum-team/mmp_practicum_fall_2018/blob/master/02_numpy/intro_to_numpy.ipynb